### ISSUE TITLE
glitch shader sending ints without sendInt doesn't work in LOVE 0.10.1

### ISSUE THREAD

**Issue by ben0x539** [eevee/neon-phase#1]
```$ love --version
LOVE 0.10.1 (Super Toast)
$ love NEON\ PHASE.love 
Error: neonphase/glitch.lua:30: Cannot convert between float and int.
stack traceback:
	[C]: in function 'send'
	neonphase/glitch.lua:30: in function 'init'
	klinklang/object.lua:11: in function 'Glitch'
	klinklang/scenes/world.lua:44: in function 'init'
	klinklang/object.lua:11: in function 'WorldScene'
	main.lua:117: in function 'load'
	[string "boot.lua"]:439: in function <[string "boot.lua"]:435>
	[C]: in function 'xpcall'
```

Immediately on startup; also about the same text in an actual window. I don't speak LOEVE, so it's not obvious to me what's wrong.

**Comment by ben0x539** [comment]
Update: I speak LOEVE now

**Comment by ben0x539** [comment]
For `shader:send` to send ints, I need 0.10.2 according to the secon to last item in https://love2d.org/wiki/0.10.2, or else I need to say `:%s/send('\(y_bands\|y_chunk\|y_min\|y_max\)'/sendInt('\1'`. Unsure if this is a bug in the code or in the stated requirements. 😛

**Comment by eevee** [comment]
It was a bug in the requirements, sorry.  :)  I fixed that a few days ago.

I could make it work both ways, but I don't have 0.10.1 on hand and can't actually guarantee it'll work there...  Is getting 0.10.2 a pain?  Is 0.10.1 the latest Ubuntu build or something?  (Still, three months later?)

**Comment by ben0x539** [comment]
I'm happy to close this with the requirements listing 0.10.2.

**Comment by ben0x539** [comment]
0.10.1 is in NixOS unstable, can't speak for Ubuntu.
