### ISSUE TITLE
My lua does not have math.mod, won't start

### ISSUE THREAD

**Issue by ktims** [eevee/neon-phase#3]
Not sure if this is a Lua version dependency or what, but replacing the one instance I found with the `%` operator gets it started.

https://gist.github.com/ktims/50d392e3f66f8a5bfb61496b90035b8c

**Comment by mistydemeo** [comment]
What version of Lua are you using?

**Comment by eevee** [comment]
That's, uh, weird — surely the same version of LÖVE always uses the same bundled version of Lua?

**Comment by ktims** [comment]
My system Lua is:
`Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio`

I'm not sure if LÖVE bundles its own Lua or uses the system one, I built it from source with the included autconf scripts.

**Comment by mistydemeo** [comment]
> That's, uh, weird — surely the same version of LÖVE always uses the same bundled version of Lua?

From the little reading I've done, math is a core library since at least 5.0; the only reference I found to a lua that doesn't include it is the [version used in PICO-8](https://gist.github.com/josefnpat/bfe4aaa5bbb44f572cd0), which seems unlikely here.

**Comment by ktims** [comment]
Did a bit more poking myself. System `lua` command has `math.mod` and it works, so I guess LÖVE does bundle its own interpreter. I check the reference documentation for [Lua 5.3](https://www.lua.org/manual/5.3/manual.html#6.7) (also 5.2) and it looks like `mod` has disappeared from `math`.

Dug a little deeper and it's documented in the [Lua 5.1 changelog](https://www.lua.org/manual/5.1/manual.html#7.2):
>  Function math.mod was renamed math.fmod. (See compile-time option LUA_COMPAT_MOD in luaconf.h.)

Maybe this should go upstream and LÖVE should be built with the flag set?

**Comment by eevee** [comment]
I have no problem using `%` here, and I'm pretty sure I use it elsewhere.  It's been in since 5.1 (which I think is the earliest anyone uses), and I think I only used `math.mod` here because it made for a visually-pleasing parallel with `math.floor`.
